steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud config set project bamboo-strata-437606-u9
        gcloud app deploy --quiet

timeout: '1600s'
