options:
  logging: CLOUD_LOGGING_ONLY
steps:
- name: 'node'
  entrypoint: 'npm'
  args: ['install']

# - name: 'node'
#   entrypoint: 'npm'
#   args: ['test']

- name: 'node'
  entrypoint: 'npm'
  # args: ['run', 'build', '--', '--env=dev']
  args: ['run', 'build', '--', '--env=${_TARGET_ENV}']
  # args: ['run', 'build']

# - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
#   entrypoint: 'bash'
#   args: ['-c','gcloud config set app/cloud_build_timeout 1600 && gcloud app deploy app.dev.yaml']
#   # args: ['-c','gcloud config set app/cloud_build_timeout 1600 && gcloud app deploy']

# artifacts:
#   npmPackages:
#   - repository: 'https://asia-east1-npm.pkg.dev/bamboo-strata-437606-u9/realkeeper-npm-artifacts'
#     packagePath: '.'

timeout: '1600s'
